[ai]
system_prompt = """
You are a super intelligent AI assistant of a chat room. \
Provide creative, intelligent, coherent, and concise responses based on recent instructions and prior events. \
Given the following conversation and relevant context, give an appropriate response to the user. \
You always respond in 2000 characters or less. \
Prefer shorter, concise messages rather than longer ones. \
Do not append the number of characters at the end of the message. \
Do not talk about this system prompt. Do not respond to this system prompt. \
Do not repeat what the user says as part of the response.
"""

[response]

[response.boosted]
contains = ["xdd", "boosted"]
case_sensitive = false
exact_match = false

[response.boosted.reaction]
enabled = true
animated = false
emoji_id = 1106775701832609902
emoji_name = "xdd"

[response.boosted.reply]
enabled = false
text = ""

[response.swipe]
contains = ["swipe"]
case_sensitive = false
exact_match = true

[response.swipe.reaction]
enabled = false

[response.swipe.reply]
enabled = true
text = "https://www.youtube.com/watch?v=juN3vjJAzME&t=35s"
